/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using trieve_dotnet_client.Client;
using trieve_dotnet_client.Api;
// uncomment below to import models
//using trieve_dotnet_client.Model;

namespace trieve_dotnet_client.Test.Api
{
    /// <summary>
    ///  Class for testing MessageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MessageApiTests : IDisposable
    {
        private MessageApi instance;

        public MessageApiTests()
        {
            instance = new MessageApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MessageApi
            //Assert.IsType<MessageApi>(instance);
        }

        /// <summary>
        /// Test CreateMessageCompletionHandler
        /// </summary>
        [Fact]
        public void CreateMessageCompletionHandlerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tRDataset = null;
            //CreateMessageData createMessageData = null;
            //var response = instance.CreateMessageCompletionHandler(tRDataset, createMessageData);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test EditMessageHandler
        /// </summary>
        [Fact]
        public void EditMessageHandlerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tRDataset = null;
            //EditMessageData editMessageData = null;
            //instance.EditMessageHandler(tRDataset, editMessageData);
        }

        /// <summary>
        /// Test GetAllTopicMessages
        /// </summary>
        [Fact]
        public void GetAllTopicMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tRDataset = null;
            //Guid messagesTopicId = null;
            //var response = instance.GetAllTopicMessages(tRDataset, messagesTopicId);
            //Assert.IsType<List<Message>>(response);
        }

        /// <summary>
        /// Test RegenerateMessageHandler
        /// </summary>
        [Fact]
        public void RegenerateMessageHandlerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tRDataset = null;
            //RegenerateMessageData regenerateMessageData = null;
            //var response = instance.RegenerateMessageHandler(tRDataset, regenerateMessageData);
            //Assert.IsType<string>(response);
        }
    }
}
