/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using trieve_dotnet_client.Client;
using trieve_dotnet_client.Api;
// uncomment below to import models
//using trieve_dotnet_client.Model;

namespace trieve_dotnet_client.Test.Api
{
    /// <summary>
    ///  Class for testing OrganizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrganizationApiTests : IDisposable
    {
        private OrganizationApi instance;

        public OrganizationApiTests()
        {
            instance = new OrganizationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrganizationApi
            //Assert.IsType<OrganizationApi>(instance);
        }

        /// <summary>
        /// Test CreateOrganization
        /// </summary>
        [Fact]
        public void CreateOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrganizationData createOrganizationData = null;
            //var response = instance.CreateOrganization(createOrganizationData);
            //Assert.IsType<Organization>(response);
        }

        /// <summary>
        /// Test DeleteOrganizationById
        /// </summary>
        [Fact]
        public void DeleteOrganizationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tROrganization = null;
            //Guid organizationId = null;
            //var response = instance.DeleteOrganizationById(tROrganization, organizationId);
            //Assert.IsType<Organization>(response);
        }

        /// <summary>
        /// Test GetOrganizationById
        /// </summary>
        [Fact]
        public void GetOrganizationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tROrganization = null;
            //Guid organizationId = null;
            //var response = instance.GetOrganizationById(tROrganization, organizationId);
            //Assert.IsType<Organization>(response);
        }

        /// <summary>
        /// Test GetOrganizationUsage
        /// </summary>
        [Fact]
        public void GetOrganizationUsageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tROrganization = null;
            //Guid organizationId = null;
            //var response = instance.GetOrganizationUsage(tROrganization, organizationId);
            //Assert.IsType<OrganizationUsageCount>(response);
        }

        /// <summary>
        /// Test GetOrganizationUsers
        /// </summary>
        [Fact]
        public void GetOrganizationUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tROrganization = null;
            //Guid organizationId = null;
            //var response = instance.GetOrganizationUsers(tROrganization, organizationId);
            //Assert.IsType<List<SlimUser>>(response);
        }

        /// <summary>
        /// Test UpdateOrganization
        /// </summary>
        [Fact]
        public void UpdateOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tROrganization = null;
            //UpdateOrganizationData updateOrganizationData = null;
            //var response = instance.UpdateOrganization(tROrganization, updateOrganizationData);
            //Assert.IsType<Organization>(response);
        }
    }
}
