/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = trieve_dotnet_client.Client.OpenAPIDateConverter;

namespace trieve_dotnet_client.Model
{
    /// <summary>
    /// AddChunkToGroupData
    /// </summary>
    [DataContract(Name = "AddChunkToGroupData")]
    public partial class AddChunkToGroupData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddChunkToGroupData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddChunkToGroupData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddChunkToGroupData" /> class.
        /// </summary>
        /// <param name="chunkId">Id of the chunk to make a member of the group. (required).</param>
        public AddChunkToGroupData(Guid chunkId = default(Guid))
        {
            this.ChunkId = chunkId;
        }

        /// <summary>
        /// Id of the chunk to make a member of the group.
        /// </summary>
        /// <value>Id of the chunk to make a member of the group.</value>
        [DataMember(Name = "chunk_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid ChunkId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddChunkToGroupData {\n");
            sb.Append("  ChunkId: ").Append(ChunkId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
