/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = trieve_dotnet_client.Client.OpenAPIDateConverter;

namespace trieve_dotnet_client.Model
{
    /// <summary>
    /// DatasetUsageCount
    /// </summary>
    [DataContract(Name = "DatasetUsageCount")]
    public partial class DatasetUsageCount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetUsageCount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DatasetUsageCount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetUsageCount" /> class.
        /// </summary>
        /// <param name="chunkCount">chunkCount (required).</param>
        /// <param name="datasetId">datasetId (required).</param>
        /// <param name="id">id (required).</param>
        public DatasetUsageCount(int chunkCount = default(int), Guid datasetId = default(Guid), Guid id = default(Guid))
        {
            this.ChunkCount = chunkCount;
            this.DatasetId = datasetId;
            this.Id = id;
        }

        /// <summary>
        /// Gets or Sets ChunkCount
        /// </summary>
        [DataMember(Name = "chunk_count", IsRequired = true, EmitDefaultValue = true)]
        public int ChunkCount { get; set; }

        /// <summary>
        /// Gets or Sets DatasetId
        /// </summary>
        [DataMember(Name = "dataset_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid DatasetId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DatasetUsageCount {\n");
            sb.Append("  ChunkCount: ").Append(ChunkCount).Append("\n");
            sb.Append("  DatasetId: ").Append(DatasetId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
