/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = trieve_dotnet_client.Client.OpenAPIDateConverter;

namespace trieve_dotnet_client.Model
{
    /// <summary>
    /// DatasetDTO
    /// </summary>
    [DataContract(Name = "DatasetDTO")]
    public partial class DatasetDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DatasetDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetDTO" /> class.
        /// </summary>
        /// <param name="clientConfiguration">clientConfiguration (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="organizationId">organizationId (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public DatasetDTO(Object clientConfiguration = default(Object), DateTime createdAt = default(DateTime), Guid id = default(Guid), string name = default(string), Guid organizationId = default(Guid), DateTime updatedAt = default(DateTime))
        {
            // to ensure "clientConfiguration" is required (not null)
            if (clientConfiguration == null)
            {
                throw new ArgumentNullException("clientConfiguration is a required property for DatasetDTO and cannot be null");
            }
            this.ClientConfiguration = clientConfiguration;
            this.CreatedAt = createdAt;
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DatasetDTO and cannot be null");
            }
            this.Name = name;
            this.OrganizationId = organizationId;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets ClientConfiguration
        /// </summary>
        [DataMember(Name = "client_configuration", IsRequired = true, EmitDefaultValue = true)]
        public Object ClientConfiguration { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name = "organization_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DatasetDTO {\n");
            sb.Append("  ClientConfiguration: ").Append(ClientConfiguration).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
