/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = trieve_dotnet_client.Client.OpenAPIDateConverter;

namespace trieve_dotnet_client.Model
{
    /// <summary>
    /// SearchChunkQueryResponseBody
    /// </summary>
    [DataContract(Name = "SearchChunkQueryResponseBody")]
    public partial class SearchChunkQueryResponseBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchChunkQueryResponseBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchChunkQueryResponseBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchChunkQueryResponseBody" /> class.
        /// </summary>
        /// <param name="scoreChunks">scoreChunks (required).</param>
        /// <param name="totalChunkPages">totalChunkPages (required).</param>
        public SearchChunkQueryResponseBody(List<ScoreChunkDTO> scoreChunks = default(List<ScoreChunkDTO>), long totalChunkPages = default(long))
        {
            // to ensure "scoreChunks" is required (not null)
            if (scoreChunks == null)
            {
                throw new ArgumentNullException("scoreChunks is a required property for SearchChunkQueryResponseBody and cannot be null");
            }
            this.ScoreChunks = scoreChunks;
            this.TotalChunkPages = totalChunkPages;
        }

        /// <summary>
        /// Gets or Sets ScoreChunks
        /// </summary>
        [DataMember(Name = "score_chunks", IsRequired = true, EmitDefaultValue = true)]
        public List<ScoreChunkDTO> ScoreChunks { get; set; }

        /// <summary>
        /// Gets or Sets TotalChunkPages
        /// </summary>
        [DataMember(Name = "total_chunk_pages", IsRequired = true, EmitDefaultValue = true)]
        public long TotalChunkPages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchChunkQueryResponseBody {\n");
            sb.Append("  ScoreChunks: ").Append(ScoreChunks).Append("\n");
            sb.Append("  TotalChunkPages: ").Append(TotalChunkPages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
