/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = trieve_dotnet_client.Client.OpenAPIDateConverter;

namespace trieve_dotnet_client.Model
{
    /// <summary>
    /// SuggestedQueriesResponse
    /// </summary>
    [DataContract(Name = "SuggestedQueriesResponse")]
    public partial class SuggestedQueriesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestedQueriesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SuggestedQueriesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestedQueriesResponse" /> class.
        /// </summary>
        /// <param name="queries">queries (required).</param>
        public SuggestedQueriesResponse(List<string> queries = default(List<string>))
        {
            // to ensure "queries" is required (not null)
            if (queries == null)
            {
                throw new ArgumentNullException("queries is a required property for SuggestedQueriesResponse and cannot be null");
            }
            this.Queries = queries;
        }

        /// <summary>
        /// Gets or Sets Queries
        /// </summary>
        [DataMember(Name = "queries", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Queries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuggestedQueriesResponse {\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
