/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing AuthQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthQuery
        //private AuthQuery instance;

        public AuthQueryTests()
        {
            // TODO uncomment below to create an instance of AuthQuery
            //instance = new AuthQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthQuery
        /// </summary>
        [Fact]
        public void AuthQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthQuery
            //Assert.IsType<AuthQuery>(instance);
        }

        /// <summary>
        /// Test the property 'InvCode'
        /// </summary>
        [Fact]
        public void InvCodeTest()
        {
            // TODO unit test for the property 'InvCode'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Fact]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }
    }
}
