/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing ChunkMetadataWithFileData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChunkMetadataWithFileDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChunkMetadataWithFileData
        //private ChunkMetadataWithFileData instance;

        public ChunkMetadataWithFileDataTests()
        {
            // TODO uncomment below to create an instance of ChunkMetadataWithFileData
            //instance = new ChunkMetadataWithFileData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChunkMetadataWithFileData
        /// </summary>
        [Fact]
        public void ChunkMetadataWithFileDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChunkMetadataWithFileData
            //Assert.IsType<ChunkMetadataWithFileData>(instance);
        }

        /// <summary>
        /// Test the property 'ChunkHtml'
        /// </summary>
        [Fact]
        public void ChunkHtmlTest()
        {
            // TODO unit test for the property 'ChunkHtml'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Fact]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'QdrantPointId'
        /// </summary>
        [Fact]
        public void QdrantPointIdTest()
        {
            // TODO unit test for the property 'QdrantPointId'
        }

        /// <summary>
        /// Test the property 'TagSet'
        /// </summary>
        [Fact]
        public void TagSetTest()
        {
            // TODO unit test for the property 'TagSet'
        }

        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }

        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
    }
}
