/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing ClientDatasetConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientDatasetConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientDatasetConfiguration
        //private ClientDatasetConfiguration instance;

        public ClientDatasetConfigurationTests()
        {
            // TODO uncomment below to create an instance of ClientDatasetConfiguration
            //instance = new ClientDatasetConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientDatasetConfiguration
        /// </summary>
        [Fact]
        public void ClientDatasetConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientDatasetConfiguration
            //Assert.IsType<ClientDatasetConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'CREATE_CHUNK_FEATURE'
        /// </summary>
        [Fact]
        public void CREATE_CHUNK_FEATURETest()
        {
            // TODO unit test for the property 'CREATE_CHUNK_FEATURE'
        }

        /// <summary>
        /// Test the property 'DATE_RANGE_VALUE'
        /// </summary>
        [Fact]
        public void DATE_RANGE_VALUETest()
        {
            // TODO unit test for the property 'DATE_RANGE_VALUE'
        }

        /// <summary>
        /// Test the property 'DOCUMENT_UPLOAD_FEATURE'
        /// </summary>
        [Fact]
        public void DOCUMENT_UPLOAD_FEATURETest()
        {
            // TODO unit test for the property 'DOCUMENT_UPLOAD_FEATURE'
        }

        /// <summary>
        /// Test the property 'FILE_NAME_KEY'
        /// </summary>
        [Fact]
        public void FILE_NAME_KEYTest()
        {
            // TODO unit test for the property 'FILE_NAME_KEY'
        }

        /// <summary>
        /// Test the property 'FILTER_ITEMS'
        /// </summary>
        [Fact]
        public void FILTER_ITEMSTest()
        {
            // TODO unit test for the property 'FILTER_ITEMS'
        }

        /// <summary>
        /// Test the property 'FRONTMATTER_VALS'
        /// </summary>
        [Fact]
        public void FRONTMATTER_VALSTest()
        {
            // TODO unit test for the property 'FRONTMATTER_VALS'
        }

        /// <summary>
        /// Test the property 'IMAGE_RANGE_END_KEY'
        /// </summary>
        [Fact]
        public void IMAGE_RANGE_END_KEYTest()
        {
            // TODO unit test for the property 'IMAGE_RANGE_END_KEY'
        }

        /// <summary>
        /// Test the property 'IMAGE_RANGE_START_KEY'
        /// </summary>
        [Fact]
        public void IMAGE_RANGE_START_KEYTest()
        {
            // TODO unit test for the property 'IMAGE_RANGE_START_KEY'
        }

        /// <summary>
        /// Test the property 'LINES_BEFORE_SHOW_MORE'
        /// </summary>
        [Fact]
        public void LINES_BEFORE_SHOW_MORETest()
        {
            // TODO unit test for the property 'LINES_BEFORE_SHOW_MORE'
        }

        /// <summary>
        /// Test the property 'SEARCH_QUERIES'
        /// </summary>
        [Fact]
        public void SEARCH_QUERIESTest()
        {
            // TODO unit test for the property 'SEARCH_QUERIES'
        }

        /// <summary>
        /// Test the property 'SUGGESTED_QUERIES'
        /// </summary>
        [Fact]
        public void SUGGESTED_QUERIESTest()
        {
            // TODO unit test for the property 'SUGGESTED_QUERIES'
        }
    }
}
