/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateDatasetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateDatasetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateDatasetRequest
        //private CreateDatasetRequest instance;

        public CreateDatasetRequestTests()
        {
            // TODO uncomment below to create an instance of CreateDatasetRequest
            //instance = new CreateDatasetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateDatasetRequest
        /// </summary>
        [Fact]
        public void CreateDatasetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateDatasetRequest
            //Assert.IsType<CreateDatasetRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientConfiguration'
        /// </summary>
        [Fact]
        public void ClientConfigurationTest()
        {
            // TODO unit test for the property 'ClientConfiguration'
        }

        /// <summary>
        /// Test the property 'DatasetName'
        /// </summary>
        [Fact]
        public void DatasetNameTest()
        {
            // TODO unit test for the property 'DatasetName'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'ServerConfiguration'
        /// </summary>
        [Fact]
        public void ServerConfigurationTest()
        {
            // TODO unit test for the property 'ServerConfiguration'
        }
    }
}
