/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMessageData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMessageDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMessageData
        //private CreateMessageData instance;

        public CreateMessageDataTests()
        {
            // TODO uncomment below to create an instance of CreateMessageData
            //instance = new CreateMessageData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMessageData
        /// </summary>
        [Fact]
        public void CreateMessageDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMessageData
            //Assert.IsType<CreateMessageData>(instance);
        }

        /// <summary>
        /// Test the property 'HighlightCitations'
        /// </summary>
        [Fact]
        public void HighlightCitationsTest()
        {
            // TODO unit test for the property 'HighlightCitations'
        }

        /// <summary>
        /// Test the property 'HighlightDelimiters'
        /// </summary>
        [Fact]
        public void HighlightDelimitersTest()
        {
            // TODO unit test for the property 'HighlightDelimiters'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'NewMessageContent'
        /// </summary>
        [Fact]
        public void NewMessageContentTest()
        {
            // TODO unit test for the property 'NewMessageContent'
        }

        /// <summary>
        /// Test the property 'StreamResponse'
        /// </summary>
        [Fact]
        public void StreamResponseTest()
        {
            // TODO unit test for the property 'StreamResponse'
        }

        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Fact]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
    }
}
