/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing EventReturn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventReturnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventReturn
        //private EventReturn instance;

        public EventReturnTests()
        {
            // TODO uncomment below to create an instance of EventReturn
            //instance = new EventReturn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventReturn
        /// </summary>
        [Fact]
        public void EventReturnInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventReturn
            //Assert.IsType<EventReturn>(instance);
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Fact]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
    }
}
