/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing MatchCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchCondition
        //private MatchCondition instance;

        public MatchConditionTests()
        {
            // TODO uncomment below to create an instance of MatchCondition
            //instance = new MatchCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchCondition
        /// </summary>
        [Fact]
        public void MatchConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchCondition
            //Assert.IsType<MatchCondition>(instance);
        }
    }
}
