/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing ReturnQueuedChunk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReturnQueuedChunkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReturnQueuedChunk
        //private ReturnQueuedChunk instance;

        public ReturnQueuedChunkTests()
        {
            // TODO uncomment below to create an instance of ReturnQueuedChunk
            //instance = new ReturnQueuedChunk();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReturnQueuedChunk
        /// </summary>
        [Fact]
        public void ReturnQueuedChunkInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReturnQueuedChunk
            //Assert.IsType<ReturnQueuedChunk>(instance);
        }

        /// <summary>
        /// Test the property 'ChunkMetadata'
        /// </summary>
        [Fact]
        public void ChunkMetadataTest()
        {
            // TODO unit test for the property 'ChunkMetadata'
        }

        /// <summary>
        /// Test the property 'PosInQueue'
        /// </summary>
        [Fact]
        public void PosInQueueTest()
        {
            // TODO unit test for the property 'PosInQueue'
        }
    }
}
