/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchGroupsResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchGroupsResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchGroupsResult
        //private SearchGroupsResult instance;

        public SearchGroupsResultTests()
        {
            // TODO uncomment below to create an instance of SearchGroupsResult
            //instance = new SearchGroupsResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchGroupsResult
        /// </summary>
        [Fact]
        public void SearchGroupsResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchGroupsResult
            //Assert.IsType<SearchGroupsResult>(instance);
        }

        /// <summary>
        /// Test the property 'Bookmarks'
        /// </summary>
        [Fact]
        public void BookmarksTest()
        {
            // TODO unit test for the property 'Bookmarks'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
    }
}
