/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchOverGroupsResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchOverGroupsResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchOverGroupsResponseBody
        //private SearchOverGroupsResponseBody instance;

        public SearchOverGroupsResponseBodyTests()
        {
            // TODO uncomment below to create an instance of SearchOverGroupsResponseBody
            //instance = new SearchOverGroupsResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchOverGroupsResponseBody
        /// </summary>
        [Fact]
        public void SearchOverGroupsResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchOverGroupsResponseBody
            //Assert.IsType<SearchOverGroupsResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'GroupChunks'
        /// </summary>
        [Fact]
        public void GroupChunksTest()
        {
            // TODO unit test for the property 'GroupChunks'
        }

        /// <summary>
        /// Test the property 'TotalChunkPages'
        /// </summary>
        [Fact]
        public void TotalChunkPagesTest()
        {
            // TODO unit test for the property 'TotalChunkPages'
        }
    }
}
