/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchWithinGroupData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchWithinGroupDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchWithinGroupData
        //private SearchWithinGroupData instance;

        public SearchWithinGroupDataTests()
        {
            // TODO uncomment below to create an instance of SearchWithinGroupData
            //instance = new SearchWithinGroupData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchWithinGroupData
        /// </summary>
        [Fact]
        public void SearchWithinGroupDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchWithinGroupData
            //Assert.IsType<SearchWithinGroupData>(instance);
        }

        /// <summary>
        /// Test the property 'DateBias'
        /// </summary>
        [Fact]
        public void DateBiasTest()
        {
            // TODO unit test for the property 'DateBias'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'GroupTrackingId'
        /// </summary>
        [Fact]
        public void GroupTrackingIdTest()
        {
            // TODO unit test for the property 'GroupTrackingId'
        }

        /// <summary>
        /// Test the property 'HighlightDelimiters'
        /// </summary>
        [Fact]
        public void HighlightDelimitersTest()
        {
            // TODO unit test for the property 'HighlightDelimiters'
        }

        /// <summary>
        /// Test the property 'HighlightResults'
        /// </summary>
        [Fact]
        public void HighlightResultsTest()
        {
            // TODO unit test for the property 'HighlightResults'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'ScoreThreshold'
        /// </summary>
        [Fact]
        public void ScoreThresholdTest()
        {
            // TODO unit test for the property 'ScoreThreshold'
        }

        /// <summary>
        /// Test the property 'SearchType'
        /// </summary>
        [Fact]
        public void SearchTypeTest()
        {
            // TODO unit test for the property 'SearchType'
        }

        /// <summary>
        /// Test the property 'UseWeights'
        /// </summary>
        [Fact]
        public void UseWeightsTest()
        {
            // TODO unit test for the property 'UseWeights'
        }
    }
}
