/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing SuggestedQueriesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuggestedQueriesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuggestedQueriesResponse
        //private SuggestedQueriesResponse instance;

        public SuggestedQueriesResponseTests()
        {
            // TODO uncomment below to create an instance of SuggestedQueriesResponse
            //instance = new SuggestedQueriesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuggestedQueriesResponse
        /// </summary>
        [Fact]
        public void SuggestedQueriesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuggestedQueriesResponse
            //Assert.IsType<SuggestedQueriesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Queries'
        /// </summary>
        [Fact]
        public void QueriesTest()
        {
            // TODO unit test for the property 'Queries'
        }
    }
}
