/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateGroupByTrackingIDData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateGroupByTrackingIDDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateGroupByTrackingIDData
        //private UpdateGroupByTrackingIDData instance;

        public UpdateGroupByTrackingIDDataTests()
        {
            // TODO uncomment below to create an instance of UpdateGroupByTrackingIDData
            //instance = new UpdateGroupByTrackingIDData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateGroupByTrackingIDData
        /// </summary>
        [Fact]
        public void UpdateGroupByTrackingIDDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateGroupByTrackingIDData
            //Assert.IsType<UpdateGroupByTrackingIDData>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }
    }
}
