/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using trieve_dotnet_client.Model;
using trieve_dotnet_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace trieve_dotnet_client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateChunkByTrackingIdData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateChunkByTrackingIdDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateChunkByTrackingIdData
        //private UpdateChunkByTrackingIdData instance;

        public UpdateChunkByTrackingIdDataTests()
        {
            // TODO uncomment below to create an instance of UpdateChunkByTrackingIdData
            //instance = new UpdateChunkByTrackingIdData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateChunkByTrackingIdData
        /// </summary>
        [Fact]
        public void UpdateChunkByTrackingIdDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateChunkByTrackingIdData
            //Assert.IsType<UpdateChunkByTrackingIdData>(instance);
        }

        /// <summary>
        /// Test the property 'ChunkHtml'
        /// </summary>
        [Fact]
        public void ChunkHtmlTest()
        {
            // TODO unit test for the property 'ChunkHtml'
        }

        /// <summary>
        /// Test the property 'GroupIds'
        /// </summary>
        [Fact]
        public void GroupIdsTest()
        {
            // TODO unit test for the property 'GroupIds'
        }

        /// <summary>
        /// Test the property 'GroupTrackingIds'
        /// </summary>
        [Fact]
        public void GroupTrackingIdsTest()
        {
            // TODO unit test for the property 'GroupTrackingIds'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }

        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
    }
}
